### PR TITLE
[FIX] Flutter 3.22 WASM fixes

### PR DESCRIPTION
**Pull request by prateekmedia**

### CODE REVIEW

**Comment by morzan1001** [comment]
@alexeyinkin could you please have a look at this pull request 😃

**Comment by kevmoo** [comment]
@nausharipov @ArinFaraj ?

**Comment by ArinFaraj** [comment]
> @nausharipov @ArinFaraj ?

Maybe this is out of place in a PR but i have switched to https://pub.dev/packages/re_editor

**Review by nausharipov — APPROVED** [review]

**Comment by kevmoo** [comment]
Thank you @nausharipov !

Can you publish the update?

**Comment by nausharipov** [comment]
I'm sorry for leaving the project on its own. I no longer work at Akvelon, but will try to keep the package up to date. I'll release a new version today.

**Comment by nausharipov** [comment]
I've requested permission and waiting for reply. 

Screenshot 2024-06-26 at 08 56 35

**Comment by nausharipov** [comment]
I've received permission and updated the package.
@kevmoo @prateekmedia @morzan1001 @ArinFaraj

Screenshot 2024-06-26 at 10 14 56

**Comment by kevmoo** [comment]
Thank you SO MUCH! 🙏

**Comment by alexeyinkin** [comment]
@kevmoo by the way, do you use this package? Where?

**Comment by kevmoo** [comment]
Hey @alexeyinkin – it's for a yet-to-be-released demo! 😄

**Pull request merged**
